// 优通英语拼读 - 课程数据（L1-L5 完整版）
// 基于 Oxford Phonics World 风格
// 自动生成 - 语法已验证

const UNITS = [
  // ========== L1: The Alphabet ==========
  {
    id: 'L1',
    emoji: '🔤',
    name: 'The Alphabet',
    zh: '字母发音',
    color: '#FF6B6B',
    phonetic_items: [
      { phonetic: 'Aa', words: ['apple', 'ant', 'ax', 'alligator'] },
      { phonetic: 'Bb', words: ['bear', 'bird', 'bed', 'banana'] },
      { phonetic: 'Cc', words: ['cat', 'cup', 'car', 'computer'] },
      { phonetic: 'Dd', words: ['dog', 'duck', 'desk', 'doll'] },
      { phonetic: 'Ee', words: ['egg', 'elbow', 'envelope', 'elephant'] },
      { phonetic: 'Ff', words: ['fish', 'fan', 'farm', 'fork'] },
      { phonetic: 'Gg', words: ['goat', 'girl', 'gorilla', 'gift'] },
      { phonetic: 'Hh', words: ['horse', 'hat', 'house', 'hot dog'] },
      { phonetic: 'Ii', words: ['igloo', 'iguana', 'insect', 'ink'] },
      { phonetic: 'Jj', words: ['jet', 'jam', 'juice', 'jacket'] },
      { phonetic: 'Kk', words: ['king', 'kite', 'key', 'kangaroo'] },
      { phonetic: 'Ll', words: ['lion', 'lamp', 'lemon', 'leaf'] },
      { phonetic: 'Mm', words: ['monkey', 'milk', 'money', 'mouse'] },
      { phonetic: 'Nn', words: ['nut', 'nest', 'net', 'nose'] },
      { phonetic: 'Oo', words: ['octopus', 'ostrich', 'olive', 'ox'] },
      { phonetic: 'Pp', words: ['pen', 'panda', 'peach', 'pineapple'] },
      { phonetic: 'Qq', words: ['queen', 'quiz', 'quilt', 'question'] },
      { phonetic: 'Rr', words: ['rabbit', 'rice', 'rose', 'robot'] },
      { phonetic: 'Ss', words: ['sun', 'soap', 'socks', 'seal'] },
      { phonetic: 'Tt', words: ['turtle', 'tiger', 'teacher', 'tent'] },
      { phonetic: 'Uu', words: ['umbrella', 'up', 'umpire', 'uncle'] },
      { phonetic: 'Vv', words: ['van', 'vest', 'violin', 'vet'] },
      { phonetic: 'Ww', words: ['web', 'watch', 'water', 'wolf'] },
      { phonetic: 'Xx', words: ['box', 'fox', 'six', 'wax'] },
      { phonetic: 'Yy', words: ['yo-yo', 'yogurt', 'yak', 'yacht'] },
      { phonetic: 'Zz', words: ['zebra', 'zero', 'zoo', 'zipper'] }
    ]
  },

  // ========== L2: Short Vowels ==========
  {
    id: 'L2',
    emoji: '🔊',
    name: 'Short Vowels',
    zh: '短元音',
    color: '#FECA57',
    phonetic_items: [
      { phonetic: 'a', words: ['cat', 'ant', 'yak', 'ax'] },
      { phonetic: 'am', words: ['ram', 'jam', 'yam', 'dam'] },
      { phonetic: 'an', words: ['fan', 'man', 'pan', 'can'] },
      { phonetic: 'ad', words: ['dad', 'pad'] },
      { phonetic: 'ag', words: ['bag', 'rag'] },
      { phonetic: 'ap', words: ['cap', 'map', 'nap', 'tap'] },
      { phonetic: 'at', words: ['bat', 'rat', 'hat', 'mat'] },
      { phonetic: 'e', words: ['web', 'egg', 'vet', 'ten'] },
      { phonetic: 'et', words: ['jet', 'net', 'wet', 'pet'] },
      { phonetic: 'en', words: ['hen', 'pen'] },
      { phonetic: 'ed', words: ['red', 'bed'] },
      { phonetic: 'i', words: ['hip', 'ink', 'zip', 'in'] },
      { phonetic: 'ip', words: ['lip', 'tip', 'sip', 'rip'] },
      { phonetic: 'ib', words: ['bib', 'rib'] },
      { phonetic: 'id', words: ['kid', 'lid'] },
      { phonetic: 'in', words: ['pin', 'fin', 'bin', 'win'] },
      { phonetic: 'ig', words: ['fig', 'wig', 'big', 'dig'] },
      { phonetic: 'it', words: ['pit', 'hit', 'sit', 'bit'] },
      { phonetic: 'ix', words: ['six', 'mix'] },
      { phonetic: 'o', words: ['fox', 'log', 'ox', 'rod'] },
      { phonetic: 'ot', words: ['pot', 'hot', 'cot', 'dot'] },
      { phonetic: 'op', words: ['top', 'mop', 'hop', 'pop'] },
      { phonetic: 'u', words: ['sun', 'up', 'jug', 'hug'] },
      { phonetic: 'ug', words: ['bug', 'rug', 'mug'] },
      { phonetic: 'ud', words: ['bud', 'mud'] },
      { phonetic: 'up', words: ['pup', 'cup'] },
      { phonetic: 'ut', words: ['nut', 'hut', 'cut'] },
      { phonetic: 'ub', words: ['cub', 'tub'] },
      { phonetic: 'um', words: ['gum', 'hum'] },
      { phonetic: 'un', words: ['bun', 'run', 'fun'] }
    ]
  },

  // ========== L3: Long Vowels ==========
  {
    id: 'L3',
    emoji: '📢',
    name: 'Long Vowels',
    zh: '长元音',
    color: '#1B4FD8',
    phonetic_items: [
      { phonetic: 'a_e', words: ['tape', 'cape', 'cane', 'mane'] },
      { phonetic: 'ame', words: ['game', 'name'] },
      { phonetic: 'ake', words: ['cake', 'lake'] },
      { phonetic: 'ate', words: ['gate', 'skate'] },
      { phonetic: 'ave', words: ['wave', 'cave'] },
      { phonetic: 'i_e', words: ['kite', 'pine', 'ripe', 'fine'] },
      { phonetic: 'ime', words: ['lime', 'time'] },
      { phonetic: 'ike', words: ['like', 'hike'] },
      { phonetic: 'ive', words: ['five', 'dive'] },
      { phonetic: 'ine', words: ['nine', 'line'] },
      { phonetic: 'o_e', words: ['home', 'cone', 'bone', 'rope'] },
      { phonetic: 'u_e', words: ['cube', 'mute', 'cute', 'mule'] },
      { phonetic: 'ai', words: ['rain', 'wait', 'nail', 'tail'] },
      { phonetic: 'ay', words: ['bay', 'day', 'say', 'pay'] },
      { phonetic: 'ee', words: ['bee', 'feet', 'seed', 'jeep'] },
      { phonetic: 'ea', words: ['leaf', 'eat', 'sea', 'meat'] },
      { phonetic: 'ey', words: ['key', 'money'] },
      { phonetic: 'y', words: ['candy', 'happy', 'spy', 'sky'] },
      { phonetic: 'igh', words: ['light', 'night', 'high', 'right'] },
      { phonetic: 'ie', words: ['pie', 'tie', 'lie', 'die'] },
      { phonetic: 'oa', words: ['boat', 'coat', 'soap', 'road'] },
      { phonetic: 'ow', words: ['bow', 'row', 'yellow', 'pillow'] },
      { phonetic: 'ue', words: ['blue', 'glue', 'clue', 'Tuesday'] },
      { phonetic: 'ui', words: ['fruit', 'suit'] },
      { phonetic: 'ew', words: ['new', 'dew'] },
      { phonetic: 'oo', words: ['moon', 'zoo', 'food', 'boot'] }
    ]
  },

  // ========== L4: Consonant Blends ==========
  {
    id: 'L4',
    emoji: '🎵',
    name: 'Consonant Blends',
    zh: '辅音连缀',
    color: '#27AE60',
    phonetic_items: [
      { phonetic: 'bl', words: ['black', 'blanket', 'blue', 'blow'] },
      { phonetic: 'cl', words: ['clock', 'club', 'clap', 'clean'] },
      { phonetic: 'br', words: ['broom', 'bride', 'brown', 'bread'] },
      { phonetic: 'cr', words: ['crab', 'crocodile', 'cry', 'cream'] },
      { phonetic: 'fl', words: ['flag', 'fly', 'flower', 'floor'] },
      { phonetic: 'gl', words: ['globe', 'glass', 'glow', 'glad'] },
      { phonetic: 'fr', words: ['frog', 'Friday', 'free', 'from'] },
      { phonetic: 'gr', words: ['green', 'grass', 'grow', 'grape'] },
      { phonetic: 'pl', words: ['plate', 'play', 'please', 'plane'] },
      { phonetic: 'sl', words: ['slide', 'sleep', 'slow', 'slip'] },
      { phonetic: 'dr', words: ['drum', 'dress', 'drive', 'drop'] },
      { phonetic: 'tr', words: ['truck', 'tree', 'train', 'try'] },
      { phonetic: 'sm', words: ['smile', 'smoke', 'small', 'smell'] },
      { phonetic: 'sn', words: ['snake', 'snow', 'snail', 'snap'] },
      { phonetic: 'sp', words: ['spoon', 'spot', 'spider', 'spin'] },
      { phonetic: 'sw', words: ['swing', 'swim', 'sweat', 'sweet'] },
      { phonetic: 'st', words: ['stop', 'test', 'stamp', 'fast', 'star'] },
      { phonetic: 'sh', words: ['shell', 'fish', 'ship', 'brush', 'shop'] },
      { phonetic: 'ch', words: ['chick', 'lunch', 'chair', 'cheese'] },
      { phonetic: 'tch', words: ['watch', 'catch', 'match', 'kitchen'] },
      { phonetic: 'ph', words: ['phone', 'dolphin', 'photo', 'elephant'] },
      { phonetic: 'wh', words: ['whale', 'white', 'when', 'where'] },
      { phonetic: 'th', words: ['this', 'that', 'three', 'teeth', 'think'] },
      { phonetic: 'ck', words: ['duck', 'rocket', 'back', 'lock'] },
      { phonetic: 'qu', words: ['queen', 'quit', 'quick', 'quiz'] },
      { phonetic: 'ng', words: ['king', 'long', 'sing', 'ring'] },
      { phonetic: 'nk', words: ['bank', 'pink', 'ink', 'monkey'] },
      { phonetic: 'nd', words: ['wind', 'hand', 'sand', 'land'] },
      { phonetic: 'nt', words: ['tent', 'paint', 'ant', 'hunt'] },
      { phonetic: 'lt', words: ['belt', 'adult', 'bolt', 'melt'] },
      { phonetic: 'mp', words: ['lamp', 'camp', 'jump', 'limp'] },
      { phonetic: 'sk', words: ['skunk', 'desk', 'sky', 'skin'] },
      { phonetic: 'sc', words: ['scale', 'school', 'scan', 'scare'] },
      { phonetic: 'spr', words: ['spray', 'spring', 'spread', 'sprout'] },
      { phonetic: 'str', words: ['string', 'strong', 'street', 'straw'] },
      { phonetic: 'spl', words: ['splash', 'splint', 'split', 'splat'] },
      { phonetic: 'squ', words: ['squid', 'square', 'squeak', 'squeeze'] },
      { phonetic: 'soft c', words: ['rice', 'city', 'ice cream', 'cell phone'] },
      { phonetic: 'soft g', words: ['giraffe', 'orange', 'giant', 'cage'] },
      { phonetic: 's /z/', words: ['rose', 'jeans', 'cheese', 'legs'] }
    ]
  },

  // ========== L5: Letter Combinations ==========
  {
    id: 'L5',
    emoji: '🔡',
    name: 'Letter Combinations',
    zh: '字母组合',
    color: '#E91E8C',
    phonetic_items: [
      { phonetic: 'ar', words: ['car', 'farm', 'star', 'card', 'park'] },
      { phonetic: 'ir', words: ['bird', 'girl', 'shirt', 'dirt'] },
      { phonetic: 'ur', words: ['nurse', 'purple', 'hurt', 'turn'] },
      { phonetic: 'er', words: ['teacher', 'sister', 'driver', 'winter'] },
      { phonetic: 'or', words: ['doctor', 'tractor', 'fork', 'corn'] },
      { phonetic: 'ou', words: ['house', 'mouse', 'cloud', 'loud'] },
      { phonetic: 'ow', words: ['cow', 'brown', 'town', 'crown'] },
      { phonetic: 'oi', words: ['coin', 'soil', 'boil', 'join'] },
      { phonetic: 'oy', words: ['toy', 'boy', 'joy', 'royal'] },
      { phonetic: 'oo (u)', words: ['book', 'foot', 'good', 'wood'] },
      { phonetic: 'u (oo)', words: ['pull', 'bush', 'full', 'push'] },
      { phonetic: 'au', words: ['sauce', 'August', 'audio', 'auto'] },
      { phonetic: 'aw', words: ['prawn', 'draw', 'saw', 'jaw'] },
      { phonetic: 'all', words: ['ball', 'tall', 'fall', 'wall'] },
      { phonetic: 'wa', words: ['water', 'walk', 'wash', 'want'] },
      { phonetic: 'or (again)', words: ['horse', 'fork', 'north', 'born'] },
      { phonetic: 'oar', words: ['roar', 'board', 'coast', 'toast'] },
      { phonetic: 'are', words: ['square', 'share', 'care', 'dare'] },
      { phonetic: 'air', words: ['chair', 'hair', 'fair', 'pair'] },
      { phonetic: 'ea (e)', words: ['bread', 'head', 'dead', 'ready'] },
      { phonetic: 'ear (air)', words: ['bear', 'pear', 'wear', 'tear'] },
      { phonetic: 'ear (ee)', words: ['ear', 'clear', 'hear', 'near'] },
      { phonetic: 'eer', words: ['deer', 'cheer', 'beer', 'engineer'] },
      { phonetic: 'a (ay)', words: ['acorn', 'baby', 'elevator', 'lady'] },
      { phonetic: 'e (ee)', words: ['he', 'she', 'me', 'we'] },
      { phonetic: 'i (ai)', words: ['tiger', 'child', 'wild', 'mild'] },
      { phonetic: 'o (ou)', words: ['cold', 'hotel', 'go', 'no'] },
      { phonetic: 'u (yu)', words: ['uniform', 'music', 'cute', 'use'] },
      { phonetic: 'a (schwa)', words: ['panda', 'gorilla', 'banana', 'umbrella'] },
      { phonetic: 'e (schwa)', words: ['chicken', 'pencil', 'lemon', 'garden'] },
      { phonetic: 'kn', words: ['knife', 'knee', 'knot', 'knock'] },
      { phonetic: 'wr', words: ['write', 'wrong', 'wrist', 'wreck'] },
      { phonetic: 'mb', words: ['lamb', 'comb', 'thumb', 'climb'] },
      { phonetic: 'rh', words: ['rhino', 'rhubarb', 'rhythm', 'rhyme'] },
      { phonetic: 'ture', words: ['picture', 'nature', 'future', 'adventure'] },
      { phonetic: 'sure', words: ['treasure', 'measure', 'pleasure'] },
      { phonetic: 'ful', words: ['beautiful', 'helpful', 'wonderful'] },
      { phonetic: 'ous', words: ['famous', 'dangerous', 'nervous'] },
      { phonetic: 'tion', words: ['station', 'competition', 'action', 'nation'] },
      { phonetic: 'sion', words: ['television', 'excursion', 'decision'] }
    ]
  }
];

module.exports = { UNITS };
